[package]
name = "terrain-gen"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "0.1.7"
lazy_static = "1.5.0"
noise = "0.9.0"
wasm-bindgen = "0.2.92"
